### ISSUE TITLE
Tests on PinField sometimes fail (source code)

### ISSUE THREAD

**Issue by vladoyoung** [formaat-design/reshaped#296]
**Describe the bug**
Probably about 50% of the times, the tests from `yarn test:unit` fail for the PinField component. The errors have always been the same and have been occurring for the last several minor updates on the Reshaped source. Basically since the PinField was implemented.

**Expected behavior**
The tests to stop failing.

**Screenshots**
Consecutive screenshots as I can't fit it all in one screenshot.
<img width="1360" alt="Pasted Graphic" src="https://github.com/user-attachments/assets/2d5cbb2a-b99c-4e31-9501-9f4f6f4c7474">
<img width="1360" alt="Pasted Graphic 1" src="https://github.com/user-attachments/assets/ca7eae66-231d-402b-804f-165885a17053">
<img width="1360" alt="Pasted Graphic 2" src="https://github.com/user-attachments/assets/67d1336d-f716-4c36-b75b-e30fd6359ec6">

**Comment by blvdmitry** [comment]
Can you provide some additional information about the environment? Like the installed package versions in case they were changed, node version, etc? I'm trying to reproduce this error but it still passed every single time for me

**Comment by vladoyoung** [comment]
Apart from the package version change from [this issue](https://github.com/formaat-design/reshaped/issues/295), I've not changed any other package versions.

Node version: v22.5.1
Yarn version: 1.22.22

I've managed to get to the same error in about 5 test runs. So I can't find a pattern yet.

I've switched my node version to v20.16.0 and it failed on the second try, although I don't think it's from the node version.

**Comment by blvdmitry** [comment]
Let's try debugging this remotely if you're ok with that since I still can't reproduce it locally. 
Does replacing the test case with the following change anything for you?

```tsx
test("handles keyboard navigation", async () => {
		render(
			<Reshaped>
				<PinField name={fixtures.name} />
			</Reshaped>
		);

		const elInput = screen.getByRole<HTMLInputElement>("textbox");

		await act(() => {
			elInput.focus();
		});

		expect(elInput.selectionStart).toEqual(0);

		await userEvent.keyboard("1");

		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(1);
		});

		await userEvent.keyboard("234");

		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(3);
			expect(elInput.selectionEnd).toEqual(4);
		});

		await userEvent.keyboard(
			"{ArrowLeft}{/ArrowLeft}{ArrowLeft}{/ArrowLeft}{ArrowLeft}{/ArrowLeft}"
		);

		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(0);
			expect(elInput.selectionEnd).toEqual(1);
		});

		await userEvent.keyboard("{ArrowRight}{/ArrowRight}{ArrowRight}{/ArrowRight}");

		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(2);
			expect(elInput.selectionEnd).toEqual(3);
		});

		expect(elInput).toHaveValue("1234");
		await userEvent.keyboard("{backspace}{/backspace}");
		expect(elInput).toHaveValue("124");

		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(2);
			expect(elInput.selectionEnd).toEqual(3);
		});

		// Switched to type mode
		await userEvent.keyboard("{ArrowRight}{/ArrowRight}");

		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(3);
		});

		// Can't move further
		await userEvent.keyboard("{ArrowRight}{/ArrowRight}");
		expect(elInput.selectionStart).toEqual(3);
	});
```

**Comment by blvdmitry** [comment]
Interesting, does it help if you try to add some artificial timeout? Having it failing in github actions too makes me quite confused 😅

**Comment by vladoyoung** [comment]
I've tried that, global async timeout and a lot of other approaches. I can't manage to get it fixed!

Strangely through, running an isolated test like `yarn test:unit src/components/PinField/tests/PinField.test.tsx` never fails. Seems like it's failing only when running alongside the other tests.

**Comment by blvdmitry** [comment]
I got it reproduced once in my CI yesterday so hopefully it keeps failing today 😅

**Comment by blvdmitry** [comment]
Another attempt, where I try to wait for every single keypress to resolve before moving on. I'm not 100% sure this is the issue but at least it stopped reproducing locally, can you check this one?

```tsx
test("handles keyboard navigation", async () => {
		render(
			<Reshaped>
				<PinField name={fixtures.name} />
			</Reshaped>
		);

		const elInput = screen.getByRole<HTMLInputElement>("textbox");

		await act(() => {
			elInput.focus();
		});

		expect(elInput.selectionStart).toEqual(0);
		expect(elInput.selectionEnd).toEqual(0);

		await userEvent.keyboard("1");

		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(1);
			expect(elInput.selectionEnd).toEqual(1);
		});

		await userEvent.keyboard("234");

		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(3);
			expect(elInput.selectionEnd).toEqual(4);
		});

		// Move back to the first character
		await userEvent.keyboard("{ArrowLeft}");
		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(2);
			expect(elInput.selectionEnd).toEqual(3);
		});
		await userEvent.keyboard("{ArrowLeft}");
		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(1);
			expect(elInput.selectionEnd).toEqual(2);
		});
		await userEvent.keyboard("{ArrowLeft}");
		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(0);
			expect(elInput.selectionEnd).toEqual(1);
		});

		// Move to the third character
		await userEvent.keyboard("{ArrowRight}");
		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(1);
			expect(elInput.selectionEnd).toEqual(2);
		});
		await userEvent.keyboard("{ArrowRight}");
		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(2);
			expect(elInput.selectionEnd).toEqual(3);
		});

		expect(elInput).toHaveValue("1234");
		await userEvent.keyboard("{backspace}");
		expect(elInput).toHaveValue("124");

		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(2);
			expect(elInput.selectionEnd).toEqual(3);
		});

		// Switched to type mode
		await userEvent.keyboard("{ArrowRight}");

		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(3);
			expect(elInput.selectionStart).toEqual(3);
		});

		// Can't move further
		await userEvent.keyboard("{ArrowRight}");
		await waitFor(() => {
			expect(elInput.selectionStart).toEqual(3);
			expect(elInput.selectionStart).toEqual(3);
		});
	});
```

**Comment by vladoyoung** [comment]
I've ran it ~20 times and none of them failed! Nice one, that's the solution!

You've probably seen this, but just dropping this warning during the tests:


```zsh
 RUNS  src/components/Calendar/tests/Calendar.test.tsx
  ● Console

    console.error
      Warning: `ReactDOMTestUtils.act` is deprecated in favor of `React.act`. Import `act` from `react` instead of `react-dom/test-utils`. See https://react.dev/warnings/react-dom-test-utils for more info.
          at Component (/Users/vladoyoung/Downloads/design-system/src/hooks/tests/useRTL.test.tsx:8:30)
          at ToastProvider (/Users/vladoyoung/Downloads/design-system/src/components/Toast/ToastProvider.tsx:63:10)
          at SingletonHotkeysProvider (/Users/vladoyoung/Downloads/design-system/src/hooks/_private/useSingletonHotkeys.tsx:157:10)
          at ReshapedInner (/Users/vladoyoung/Downloads/design-system/src/components/Reshaped/Reshaped.tsx:17:10)
          at div
          at Theme (/Users/vladoyoung/Downloads/design-system/src/components/Theme/Theme.tsx:12:10)
          at GlobalColorMode (/Users/vladoyoung/Downloads/design-system/src/components/Theme/GlobalColorMode.tsx:10:10)
          at Reshaped (/Users/vladoyoung/Downloads/design-system/src/components/Reshaped/Reshaped.tsx:32:10)

       9 |
      10 | 	React.useEffect(() => {
    > 11 | 		act(() => setRTL(true));
         | 		   ^
      12 | 	}, [setRTL]);
      13 |
      14 | 	return <div>{rtl}</div>;

      at printWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:71:30)
      at error (node_modules/react-dom/cjs/react-dom-test-utils.development.js:45:7)
      at actWithWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1736:7)
      at src/hooks/tests/useRTL.test.tsx:11:6
      at commitHookEffectListMount (node_modules/react-dom/cjs/react-dom.development.js:23189:26)
      at commitPassiveMountOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24970:11)
      at commitPassiveMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24930:9)
      at commitPassiveMountEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24917:7)
      at commitPassiveMountEffects (node_modules/react-dom/cjs/react-dom.development.js:24905:3)
      at flushPassiveEffectsImpl (node_modules/react-dom/cjs/react-dom.development.js:27078:3)
      at flushPassiveEffects (node_modules/react-dom/cjs/react-dom.development.js:27023:14)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26115:3)
      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:26998:3)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:26721:5)
      at finishConcurrentRender (node_modules/react-dom/cjs/react-dom.development.js:26020:9)
      at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25848:7)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at act (node_modules/react/cjs/react.development.js:2582:11)
      at node_modules/@testing-library/react/dist/act-compat.js:47:25
      at renderRoot (node_modules/@testing-library/react/dist/pure.js:180:26)
      at render (node_modules/@testing-library/react/dist/pure.js:271:10)
      at Object.<anonymous> (src/hooks/tests/useRTL.test.tsx:19:9)
```
