### ISSUE TITLE
Source code failing tests

### ISSUE THREAD

**Issue by vladoyoung** [formaat-design/reshaped#346]
**Describe the bug**
This might depend on the user's machine and how much load it can handle, but **_inconsistently_** some tests fail for different reasons.

For example for Tooltip, but I've noticed other tests failing with the `Exceeded timeout of 5000 ms for a test` error:

```zsh
 FAIL  src/components/Tooltip/tests/Tooltip.test.tsx (9.789 s)
  ● Components/Tooltip › works as uncontrolled

    expect(received).toBeInTheDocument()

    received value must be an HTMLElement or an SVGElement.
    Received has value: null

    Ignored nodes: comments, script, style
    <html
      data-rs-color-mode="light"
      data-rs-theme="reshaped"
      dir="ltr"
    >
      <head />
      <body>
        <div>
          <div
            class=" root  root"
          >
            <button
              aria-describedby=":r4:"
              class=" root  root --color-neutral --variant-solid  --size-medium"
              data-rs-aligner-target="true"
              type="button"
            >
              <span
                class="text"
              >
                Text
              </span>
            </button>
          </div>
        </div>
      </body>
    </html>

      46 |
      47 | 		waitFor(() => {
    > 48 | 			expect(screen.queryByText(fixtures.content)).toBeInTheDocument();
         | 			                                             ^
      49 | 			expect(handleOpen).toBeCalledTimes(1);
      50 | 		});
      51 |

      at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:325:30)
      at Object.throwingMatcher [as toBeInTheDocument] (node_modules/expect/build/index.js:326:15)
      at src/components/Tooltip/tests/Tooltip.test.tsx:48:49
      at runWithExpensiveErrorDiagnosticsDisabled (node_modules/@testing-library/dom/dist/config.js:47:12)
      at checkCallback (node_modules/@testing-library/dom/dist/wait-for.js:124:77)
      at checkRealTimersCallback (node_modules/@testing-library/dom/dist/wait-for.js:118:16)
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:520:19)

  ● Components/Tooltip › works as uncontrolled

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      25 | 	});
      26 |
    > 27 | 	test("works as uncontrolled", async () => {
         | 	^
      28 | 		const handleOpen = jest.fn();
      29 | 		const handleClose = jest.fn();
      30 |

      at src/components/Tooltip/tests/Tooltip.test.tsx:27:2
      at Object.<anonymous> (src/components/Tooltip/tests/Tooltip.test.tsx:12:1)
```

<hr/>

However, MenuItem test always fail _**consistently**_:

```zsh
 FAIL  src/components/MenuItem/tests/MenuItem.test.tsx (14.62 s)
  ● Components/MenuItem › renders children

    TestingLibraryElementError: Unable to find an element with the text: Start. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    Ignored nodes: comments, script, style
    <body>
      <div>
        <span
          class=" root  root  --size-medium --color-primary"
          data-rs-aligner-target="true"
        >
          <div
            class=" root  --position-relative  --align-center --flex --direction-row --nowrap"
            style="--rs-view-gap-s: 2;"
          >
            Start
            <div
              class=" item  content item--grow"
            >
              Content
            </div>
            End
          </div>
        </span>
      </div>
    </body>

      26 |
      27 | 		expect(screen.getByText(fixtures.content)).toBeInTheDocument();
    > 28 | 		expect(screen.getByText(fixtures.start)).toBeInTheDocument();
         | 		              ^
      29 | 		expect(screen.getByText(fixtures.end)).toBeInTheDocument();
      30 | 	});
      31 |

      at Object.getElementError (node_modules/@testing-library/dom/dist/config.js:37:19)
      at node_modules/@testing-library/dom/dist/query-helpers.js:76:38
      at node_modules/@testing-library/dom/dist/query-helpers.js:52:17
      at node_modules/@testing-library/dom/dist/query-helpers.js:95:19
      at Object.<anonymous> (src/components/MenuItem/tests/MenuItem.test.tsx:28:17)
```

**Environment (please complete the following information):**
Node v20.16.0
Yarn 1.22.22
Started happening since Reshaped 3.2.1 (source code applied to our package)

I'm assuming that like last time you won't be able to reproduce this on your machine, so let me know if you need any more info or testing on my side!

**Comment by mareksed** [comment]
On 3.2.1 MenuItem was failing also on my machine, just raw source codes no changes. 
On next path it was ok

**Comment by blvdmitry** [comment]
MenuItem tests were fixed indeed, that was related to testing out react 19 compatibility which needed an additional wrapper in the test examples around the string slots. I'll try to reproduce the Tooltip test issues

**Comment by blvdmitry** [comment]
Is this still happening for you in 3.3?

**Comment by vladoyoung** [comment]
I might not be able to test this for some time, but I'll let you know as soon as possible @blvdmitry

**Comment by vladoyoung** [comment]
@blvdmitry 3.2.6 seems to have fixed this! The first `yarn test:unit` took around 400 seconds, which I think is slow, but them every other test is around 40 seconds. Nevertheless, the slow tests are more likely to be from my machine. Thanks for the fix!
